import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { 
  DollarSign, 
  Users, 
  TrendingUp, 
  Gift, 
  Copy, 
  Share2,
  Star,
  Target,
  Award,
  Link,
  Download
} from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';

interface Affiliate {
  id: string;
  affiliate_code: string;
  commission_rate: number;
  total_earnings: number;
  total_referrals: number;
  status: string;
}

interface Referral {
  id: string;
  referral_code: string;
  conversion_date: string;
  commission_earned: number;
  status: string;
}

export function AffiliateSystem() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [affiliate, setAffiliate] = useState<Affiliate | null>(null);
  const [referrals, setReferrals] = useState<Referral[]>([]);
  const [loading, setLoading] = useState(true);
  const [isRegistering, setIsRegistering] = useState(false);

  useEffect(() => {
    if (user) {
      fetchAffiliateData();
    }
  }, [user]);

  const fetchAffiliateData = async () => {
    try {
      const { data: affiliateData, error: affiliateError } = await supabase
        .from('affiliates')
        .select('*')
        .eq('user_id', user?.id)
        .single();

      if (affiliateError && affiliateError.code !== 'PGRST116') {
        throw affiliateError;
      }

      if (affiliateData) {
        setAffiliate(affiliateData);
        
        // Fetch referrals
        const { data: referralData, error: referralError } = await supabase
          .from('affiliate_referrals')
          .select('*')
          .eq('affiliate_id', affiliateData.id)
          .order('created_at', { ascending: false });

        if (referralError) throw referralError;
        setReferrals(referralData || []);
      }
    } catch (error) {
      console.error('Error fetching affiliate data:', error);
    } finally {
      setLoading(false);
    }
  };

  const registerAsAffiliate = async () => {
    if (!user) return;
    
    setIsRegistering(true);
    try {
      const { data, error } = await supabase
        .from('affiliates')
        .insert({
          user_id: user.id,
          affiliate_code: '', // Will be generated by trigger
          commission_rate: 10.00,
          status: 'active'
        })
        .select()
        .single();

      if (error) throw error;

      // Add affiliate role
      await supabase
        .from('user_roles')
        .insert({
          user_id: user.id,
          role: 'affiliate'
        });

      setAffiliate(data);
      toast({
        title: "Bem-vindo ao programa de afiliados!",
        description: "Sua conta foi criada com sucesso. Comece a ganhar agora!",
      });
    } catch (error) {
      console.error('Error registering affiliate:', error);
      toast({
        title: "Erro",
        description: "Não foi possível criar sua conta de afiliado.",
        variant: "destructive",
      });
    } finally {
      setIsRegistering(false);
    }
  };

  const copyReferralLink = async () => {
    if (!affiliate) return;
    
    const referralLink = `${window.location.origin}/?ref=${affiliate.affiliate_code}`;
    try {
      await navigator.clipboard.writeText(referralLink);
      toast({
        title: "Link copiado!",
        description: "Seu link de referência foi copiado para a área de transferência.",
      });
    } catch (error) {
      toast({
        title: "Erro",
        description: "Não foi possível copiar o link.",
        variant: "destructive",
      });
    }
  };

  const shareReferralLink = async () => {
    if (!affiliate) return;
    
    const referralLink = `${window.location.origin}/?ref=${affiliate.affiliate_code}`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Junte-se ao Lucraí',
          text: 'Descubra o melhor sistema de gestão para restaurantes!',
          url: referralLink,
        });
      } catch (error) {
        console.error('Error sharing:', error);
      }
    } else {
      copyReferralLink();
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (!affiliate) {
    return (
      <div className="min-h-[600px] flex items-center justify-center">
        <Card className="w-full max-w-md">
          <CardContent className="p-8 text-center space-y-6">
            <div className="space-y-4">
              <div className="w-16 h-16 bg-gradient-to-br from-primary to-primary/80 rounded-full flex items-center justify-center mx-auto">
                <DollarSign className="h-8 w-8 text-white" />
              </div>
              <div className="space-y-2">
                <h2 className="text-2xl font-bold">Programa de Afiliados</h2>
                <p className="text-muted-foreground">
                  Ganhe comissões indicando o Lucraí para outros restaurantes
                </p>
              </div>
            </div>
            
            <div className="space-y-4">
              <div className="grid grid-cols-3 gap-4 text-center">
                <div>
                  <p className="text-2xl font-bold text-primary">10%</p>
                  <p className="text-xs text-muted-foreground">Comissão</p>
                </div>
                <div>
                  <p className="text-2xl font-bold text-primary">R$ 50</p>
                  <p className="text-xs text-muted-foreground">Por venda</p>
                </div>
                <div>
                  <p className="text-2xl font-bold text-primary">∞</p>
                  <p className="text-xs text-muted-foreground">Sem limite</p>
                </div>
              </div>
              
              <Button 
                onClick={registerAsAffiliate}
                disabled={isRegistering}
                className="w-full"
                size="lg"
              >
                {isRegistering ? (
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                ) : (
                  <Star className="h-4 w-4 mr-2" />
                )}
                Tornar-se Afiliado
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  const nextLevel = Math.ceil(affiliate.total_referrals / 10) * 10;
  const progress = (affiliate.total_referrals / nextLevel) * 100;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <h1 className="text-3xl font-bold tracking-tight text-foreground flex items-center gap-3">
            <Award className="h-8 w-8 text-primary" />
            Painel do Afiliado
          </h1>
          <p className="text-muted-foreground">
            Acompanhe seus ganhos e compartilhe o Lucraí
          </p>
        </div>
        <Badge className="bg-green-100 text-green-800">
          {affiliate.status === 'active' ? 'Ativo' : 'Inativo'}
        </Badge>
      </div>

      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <DollarSign className="h-8 w-8 text-green-500" />
              <div>
                <p className="text-2xl font-bold">R$ {affiliate.total_earnings.toFixed(2)}</p>
                <p className="text-sm text-muted-foreground">Total Ganho</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <Users className="h-8 w-8 text-blue-500" />
              <div>
                <p className="text-2xl font-bold">{affiliate.total_referrals}</p>
                <p className="text-sm text-muted-foreground">Indicações</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <TrendingUp className="h-8 w-8 text-purple-500" />
              <div>
                <p className="text-2xl font-bold">{affiliate.commission_rate}%</p>
                <p className="text-sm text-muted-foreground">Comissão</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center space-x-2">
              <Target className="h-8 w-8 text-orange-500" />
              <div>
                <p className="text-2xl font-bold">{nextLevel - affiliate.total_referrals}</p>
                <p className="text-sm text-muted-foreground">Para próximo nível</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Progress */}
      <Card>
        <CardContent className="p-6">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="font-medium">Progresso para o próximo nível</h3>
              <span className="text-sm text-muted-foreground">
                {affiliate.total_referrals}/{nextLevel} indicações
              </span>
            </div>
            <Progress value={progress} className="h-2" />
          </div>
        </CardContent>
      </Card>

      <Tabs defaultValue="dashboard" className="space-y-4">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
          <TabsTrigger value="referrals">Indicações</TabsTrigger>
          <TabsTrigger value="materials">Materiais</TabsTrigger>
        </TabsList>

        <TabsContent value="dashboard" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Seu Link de Indicação</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center space-x-2">
                <Input
                  value={`${window.location.origin}/?ref=${affiliate.affiliate_code}`}
                  readOnly
                  className="font-mono text-sm"
                />
                <Button onClick={copyReferralLink} variant="outline">
                  <Copy className="h-4 w-4" />
                </Button>
                <Button onClick={shareReferralLink} variant="outline">
                  <Share2 className="h-4 w-4" />
                </Button>
              </div>
              <p className="text-sm text-muted-foreground">
                Código: <span className="font-mono font-bold">{affiliate.affiliate_code}</span>
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Como funciona</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="text-center space-y-3">
                  <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                    <Link className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="font-medium">1. Compartilhe</h3>
                  <p className="text-sm text-muted-foreground">
                    Envie seu link para restaurantes interessados
                  </p>
                </div>
                <div className="text-center space-y-3">
                  <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                    <Users className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="font-medium">2. Conversão</h3>
                  <p className="text-sm text-muted-foreground">
                    Quando se cadastram, você ganha uma indicação
                  </p>
                </div>
                <div className="text-center space-y-3">
                  <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                    <DollarSign className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="font-medium">3. Ganhe</h3>
                  <p className="text-sm text-muted-foreground">
                    Receba {affiliate.commission_rate}% de comissão sobre cada venda
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="referrals" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Histórico de Indicações</CardTitle>
            </CardHeader>
            <CardContent>
              {referrals.length > 0 ? (
                <div className="space-y-4">
                  {referrals.map((referral) => (
                    <div key={referral.id} className="flex items-center justify-between p-4 border rounded-lg">
                      <div>
                        <p className="font-medium">Código: {referral.referral_code}</p>
                        <p className="text-sm text-muted-foreground">
                          {referral.conversion_date ? 
                            new Date(referral.conversion_date).toLocaleDateString() : 
                            'Pendente'
                          }
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="font-bold text-green-600">
                          R$ {referral.commission_earned.toFixed(2)}
                        </p>
                        <Badge variant={referral.status === 'converted' ? 'default' : 'secondary'}>
                          {referral.status === 'converted' ? 'Convertido' : 'Pendente'}
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8">
                  <Users className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                  <p className="text-muted-foreground">Nenhuma indicação ainda</p>
                  <p className="text-sm text-muted-foreground">
                    Compartilhe seu link para começar a ganhar!
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="materials" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Materiais de Marketing</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <h3 className="font-medium">Textos para compartilhar</h3>
                  <div className="space-y-3">
                    <div className="p-4 bg-muted rounded-lg">
                      <p className="text-sm">
                        "Descobri o Lucraí e mudou completamente como gerencio meu restaurante! 
                        Sistema completo de gestão financeira, estoque e muito mais. 
                        Teste grátis: {window.location.origin}/?ref={affiliate.affiliate_code}"
                      </p>
                      <Button size="sm" variant="outline" className="mt-2">
                        <Copy className="h-3 w-3 mr-1" />
                        Copiar
                      </Button>
                    </div>
                  </div>
                </div>
                <div className="space-y-4">
                  <h3 className="font-medium">Banners</h3>
                  <div className="space-y-3">
                    <div className="p-6 bg-gradient-to-r from-primary to-primary/80 rounded-lg text-white text-center">
                      <h4 className="font-bold">LUCRAÍ</h4>
                      <p className="text-sm">Gestão Inteligente para Restaurantes</p>
                    </div>
                    <Button size="sm" variant="outline" className="w-full">
                      <Download className="h-3 w-3 mr-1" />
                      Baixar Banner
                    </Button>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}